#ifndef ENUMS_HPP
#define ENUMS_HPP

enum Setings {
    MAX_HABITATS = 11,
    MAX_RACES = 36
};

enum mainMenu {
    ADD_ANIMAL = 1,
    DISPLAY_ANIMALS,
    SORT_ANIMALS,
    UPDATE_ANIMAL,
    DELETE_ANIMAL,
    SEARCH_ANIMALS,
    DISPLAY_STATISTICS,
    EXIT
};

enum addMenu {
    ADD_ONE_ANIMAL = 1,
    ADD_MULTIPLE_ANIMALS,
    RETURN_TO_MAIN_MENU_FROM_ADD
};

enum displayMenu {
    DISPLAY_ALL_ANIMALS = 1,
    DISPLAY_BY_HABITAT,
    DISPLAY_BY_RACE,
    RETURN_TO_MAIN_MENU_FROM_DISPLAY
};

enum sortMenu {
    SORT_BY_NAME = 1,
    SORT_BY_AGE,
    SORT_BY_HABITAT,
    SORT_BY_RACE,
    SORT_BY_WEIGHT,
    RETURN_TO_MAIN_MENU_FROM_SORT
};

enum updateMenu {
    UPDATE_NAME = 1,
    UPDATE_AGE,
    UPDATE_HABITAT,
    UPDATE_RACE,
    UPDATE_WEIGHT,
    RETURN_TO_MAIN_MENU_FROM_UPDATE
};

enum searchMenu {
    SEARCH_BY_ID = 1,
    SEARCH_BY_NAME,
    SEARCH_BY_AGE,
    SEARCH_BY_HABITAT,
    SEARCH_BY_RACE,
    SEARCH_BY_WEIGHT,
    SEARCH_BY_AGE_RANGE,
    SEARCH_BY_WEIGHT_RANGE,
    RETURN_TO_MAIN_MENU_FROM_SEARCH
};

enum statisticsMenu {
    ANIMAL_COUNT = 1,
    AVG_AGE,
    AVG_WEIGHT,
    COUNT_BY_HABITAT,
    COUNT_BY_RACE,
    OLDEST_ANIMAL,
    YOUNGEST_ANIMAL,
    HEAVIEST_ANIMAL,
    LIGHTEST_ANIMAL,
    RETURN_TO_MAIN_MENU_FROM_STATISTICS
};

#endif